version: "3.8"
services:
mysql:
        container_name: mysql
        ports: 
            - 4306:3306
        environment:
            - MYSQL_DATABASE=interfell
            - MYSQL_ROOT_PASSWORD=Interfell
        volumes:
            - ./src/DataBase/:/docker-entrypoint-initdb.d/
        image: mysql:8.2